name: Flutter_Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
      - name: Prepare google-services.json
        run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' >> android/app/google-services.json
      - name: Prepare firebase_app_id_file.json
        run: |
          echo '${{ secrets.FIREBASE_APP_ID_FILE_JSON }}' >> ios/firebase_app_id_file.json
      - name: Restore packages
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage --dart-define FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} --dart-define FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} --dart-define FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} --dart-define FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} --dart-define FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} --dart-define FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }} --dart-define FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} --dart-define FIREBASE_IOS_CLIENT_ID=${{ secrets.FIREBASE_IOS_CLIENT_ID }} --dart-define FIREBASE_IOS_BUNDLE_ID=${{ secrets.FIREBASE_IOS_BUNDLE_ID }}
      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash
        shell: bash
